name: check

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    tests:
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest ]
                platform-version: [ 2020.3 ]
                dove-version: [ 1.0.0 ]

        runs-on: ${{ matrix.os }}
        env:
            ORG_GRADLE_PROJECT_intellijVersion: ${{ matrix.platform-version }}

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: 11

            -   name: Set dove binary name (linux)
                if: matrix.os == 'ubuntu-latest'
                run: echo "DOVE_BINARY_NAME=dove-${{ matrix.dove-version }}-linux-x86_64" >> $GITHUB_ENV
#                run: echo "::set-env name=DOVE_BINARY_NAME=dove-${{ matrix.dove-version }}-linux-x86_64"

#            -   name: Set dove binary name (macos)
#                if: matrix.os == 'macos-latest'
#                run: echo "::set-env name=DOVE_BINARY_NAME=dove-${{ matrix.dove-version }}-mac-x86_64"

            -   name: Set dove binary name (windows)
                if: matrix.os == 'windows-latest'
                run: echo "DOVE_BINARY_NAME=dove-${{ matrix.dove-version }}-win-x86_64.exe" >> $GITHUB_ENV

            -   name: Fetch dove executable from move-tools releases
                uses: dsaltares/fetch-gh-release-asset@master
                with:
                    repo: "dfinance/move-tools"
                    version: "tags/${{ matrix.dove-version }}"
                    file: ${{ env.DOVE_BINARY_NAME }}

            -   name: Rename dove executable and set proper permissions
                run: mv ./${{ env.DOVE_BINARY_NAME }} dove && chmod +x ./dove

            -   name: Build
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: "assemble testClasses -Pkotlin.incremental=false --no-daemon"

            -   name: Check
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: "check -Pkotlin.incremental=false --no-daemon"

            -   name: Verify plugin
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: ":verifyPlugin"


